In [1]:
# HuggingFace Login
import os
from dotenv import load_dotenv
from huggingface_hub import login
load_dotenv()
hf_token = os.getenv("HUGGING_FACE_TOKEN")
login(hf_token)

In [2]:
import pandas as pd
from datasets import Dataset, ClassLabel
import numpy as np
import random
import torch
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from peft import LoraConfig, get_peft_model
from transformers import TrainingArguments
from transformers import Trainer
from transformers import EarlyStoppingCallback
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.metrics import confusion_matrix, classification_report
from torch.utils.data import DataLoader
import gc
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from transformers import pipeline
from datasets import concatenate_datasets

In [3]:
ZERO_SHOT_MODELS = [
    "cross-encoder/nli-MiniLM2-L6-H768",
    "typeform/distilbert-base-uncased-mnli",
    "MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary",
    "tasksource/deberta-small-long-nli",
    "MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33",
    "cmarkea/distilcamembert-base-nli",
    "MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33",
    "MoritzLaurer/deberta-v3-base-zeroshot-v1"
]

LABELS = ["met palliative care needs", "unmet palliative care needs"]
LABEL_TO_NUM = {"met palliative care needs": 0, "unmet palliative care needs": 1}
LABEL_EXPANSIONS = {
    "met palliative care needs": [
        "palliative care needs are adequately met",
        "symptoms and care needs are well managed",
        "the patient is receiving appropriate palliative care",
        "care needs are sufficiently addressed"
    ],
    "unmet palliative care needs": [
        "palliative care needs are not adequately met",
        "symptoms or care needs are poorly managed",
        "the patient requires additional palliative care support",
        "care needs are not sufficiently addressed"
    ]
}

HYPOTHESIS_TEMPLATES = [
    # Generic hypothesis templates.
    "This example is about {}.",
    # Generic medical hypothesis templates. 
    "The patient's palliative care needs are {}.",
    "Overall, the patient's care needs are {}.",
    "From this note, it can be inferred that {}.",
    "This clinical note indicates that the patient's care needs are {}.",
    "Based on this note, the patient's care needs are {}.",
    # Clinical language.
    "The patient's condition suggests that {}.",
    "This note suggests that the patient is experiencing {}.",
    "The patient's current situation reflects {}.",
    # Care quality framing.
    "The patient's symptoms and care needs are {}.",
    "The patient's care is {}.",
    # Documentation style focus.
    "This note indicates a situation where {}.",
    "The note documents that {}.",
    "The record indicates that {}.",
    "The clinical documentation suggests that {}.",
]

In [4]:
# Set random states.
def set_random_states(random_state):
    # Set various random seeds.
    np.random.seed(random_state)
    random.seed(random_state)
    torch.manual_seed(random_state)
    torch.cuda.manual_seed_all(random_state)
    os.environ["PYTHONHASHSEED"] = str(random_state)
    os.environ["TOKENIZERS_PARALLELISM"] = "false"
    try:
        torch.use_deterministic_algorithms(True)
    except Exception:
        pass
    return random_state

RANDOM_STATE = set_random_states(1618)

In [5]:
# Load the dataset
df = pd.read_csv("./dataSyntheticAll.csv")
dataset = Dataset.from_pandas(df)

# Map dataset labels to 1s or 0s.
label_map = {
    "met palliative care needs": 0,
    "unmet palliative care needs": 1
}

dataset = dataset.map(lambda x: {"label": label_map[f"{x["needs"]} palliative care needs"]})


label_feature = ClassLabel(names=["met palliative care needs", "unmet palliative care needs"])
dataset = dataset.cast_column("label", label_feature)

Map:   0%|          | 0/5783 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/5783 [00:00<?, ? examples/s]

In [6]:
# Split the dataset. (80/10/10)
dataset = dataset.train_test_split(test_size=0.2, seed=RANDOM_STATE, stratify_by_column="label")

train_dataset = dataset["train"]
temp_dataset = dataset["test"]

temp_split = temp_dataset.train_test_split(test_size=0.5, seed=RANDOM_STATE, stratify_by_column="label")

val_dataset = temp_split["train"]
test_dataset = temp_split["test"]

all_dataset = concatenate_datasets([train_dataset, val_dataset, test_dataset])

# Check distributions.
def check_distribution(dataset, name):
    df = dataset.to_pandas()
    counts = df["label"].value_counts(normalize=True)
    print(f"{name} distribution:")
    print(counts)

check_distribution(train_dataset, "Train")
check_distribution(val_dataset, "Validation")
check_distribution(test_dataset, "Test")
check_distribution(all_dataset, "All Data")

Train distribution:
label
0    0.502162
1    0.497838
Name: proportion, dtype: float64
Validation distribution:
label
0    0.50173
1    0.49827
Name: proportion, dtype: float64
Test distribution:
label
0    0.502591
1    0.497409
Name: proportion, dtype: float64
All Data distribution:
label
0    0.502162
1    0.497838
Name: proportion, dtype: float64

In [7]:
# Make evaluation function.
def evaluate_model(preds, labels):
    acc = accuracy_score(labels, preds)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="binary"
    )
    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

In [8]:
results = {}
device = 0 if torch.cuda.is_available() else -1

def run_models(dataset, hypo_temp="This clinical note indicates that {}."):
    for model_name in ZERO_SHOT_MODELS:
        print(f"\nRunning zero-shot model: {model_name}")

        classifier = pipeline(
            "zero-shot-classification",
            model=model_name,
            device=device,
        )

        texts = [ex["report"] for ex in dataset]
        true_labels = [ex["label"] for ex in dataset]

        # Flatten expanded labels.
        flat_labels = []
        label_map = {}

        for base_label, expansions in LABEL_EXPANSIONS.items():
            for exp in expansions:
                flat_labels.append(exp)
                label_map[exp] = base_label

        # Run model.
        outputs = classifier(
            texts,
            candidate_labels=flat_labels,
            hypothesis_template=hypo_temp,
            batch_size=8
        )

        preds = []

        # Aggregate scores per base label.
        for o in outputs:
            scores_by_class = {k: 0.0 for k in LABEL_EXPANSIONS.keys()}

            for label, score in zip(o["labels"], o["scores"]):
                base_label = label_map[label]
                scores_by_class[base_label] += score

            # Pick best aggregated label.
            pred = max(scores_by_class, key=scores_by_class.get)
            preds.append(pred)
        numeric_preds = [0 if pred == "met palliative care needs" else 1 for pred in preds]
        metrics = evaluate_model(numeric_preds, true_labels)

        # Inner dictionary creation.
        if model_name not in results:
            results[model_name] = {}  

        results[model_name][hypo_temp] = metrics

        # Output.
        print("----------------------------------------------")
        print("--------------- Metric Results ---------------")
        print(f"\nModel: {model_name} \nHypothesis Template: {hypo_temp}")
        for k, v in metrics.items():
            print(f"{k}: {v:.4f}")

        print("--------------- Confusion Matrix ---------------")
        print(confusion_matrix(true_labels, numeric_preds))

        print("--------------- Classification Report ---------------")
        print(classification_report(true_labels, numeric_preds))

        print("----------------------------------------------\n\n\n")

        # Free memory.
        del classifier
        torch.cuda.empty_cache()
        gc.collect()

    return results

In [9]:
# Run all hypothesis templates.
all_results = []
for template in HYPOTHESIS_TEMPLATES:
    all_results.append(run_models(all_dataset, hypo_temp=template))

# Save in DataFrame.
rows = []

for model_name, templates in results.items():
    for hypo_template, metrics in templates.items():
        row = {"model": model_name, "hypothesis_template": hypo_template}
        row.update(metrics)
        rows.append(row)

# Save DataFrame.
all_df = pd.DataFrame(rows)
all_df.to_csv('./all_data_all_zero_shot_results.csv', index=False)

Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: This example is about {}.
accuracy: 0.6599
precision: 0.7747
recall: 0.4467
f1: 0.5666
--------------- Confusion Matrix ---------------
[[2530  374]
 [1593 1286]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.61      0.87      0.72      2904
           1       0.77      0.45      0.57      2879

    accuracy                           0.66      5783
   macro avg       0.69      0.66      0.64      5783
weighted avg       0.69      0.66      0.64      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: This example is about {}.
accuracy: 0.7261
precision: 0.6864
recall: 0.8281
f1: 0.7506
--------------- Confusion Matrix ---------------
[[1815 1089]
 [ 495 2384]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.79      0.62      0.70      2904
           1       0.69      0.83      0.75      2879

    accuracy                           0.73      5783
   macro avg       0.74      0.73      0.72      5783
weighted avg       0.74      0.73      0.72      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: This example is about {}.
accuracy: 0.7069
precision: 0.6582
recall: 0.8555
f1: 0.7440
--------------- Confusion Matrix ---------------
[[1625 1279]
 [ 416 2463]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.80      0.56      0.66      2904
           1       0.66      0.86      0.74      2879

    accuracy                           0.71      5783
   macro avg       0.73      0.71      0.70      5783
weighted avg       0.73      0.71      0.70      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: This example is about {}.
accuracy: 0.7022
precision: 0.9031
recall: 0.4502
f1: 0.6008
--------------- Confusion Matrix ---------------
[[2765  139]
 [1583 1296]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.64      0.95      0.76      2904
           1       0.90      0.45      0.60      2879

    accuracy                           0.70      5783
   macro avg       0.77      0.70      0.68      5783
weighted avg       0.77      0.70      0.68      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: This example is about {}.
accuracy: 0.7463
precision: 0.7406
recall: 0.7548
f1: 0.7476
--------------- Confusion Matrix ---------------
[[2143  761]
 [ 706 2173]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.75      0.74      0.75      2904
           1       0.74      0.75      0.75      2879

    accuracy                           0.75      5783
   macro avg       0.75      0.75      0.75      5783
weighted avg       0.75      0.75      0.75      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: This example is about {}.
accuracy: 0.5476
precision: 0.6804
recall: 0.1723
f1: 0.2749
--------------- Confusion Matrix ---------------
[[2671  233]
 [2383  496]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.53      0.92      0.67      2904
           1       0.68      0.17      0.27      2879

    accuracy                           0.55      5783
   macro avg       0.60      0.55      0.47      5783
weighted avg       0.60      0.55      0.47      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: This example is about {}.
accuracy: 0.7401
precision: 0.7614
recall: 0.6961
f1: 0.7273
--------------- Confusion Matrix ---------------
[[2276  628]
 [ 875 2004]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.72      0.78      0.75      2904
           1       0.76      0.70      0.73      2879

    accuracy                           0.74      5783
   macro avg       0.74      0.74      0.74      5783
weighted avg       0.74      0.74      0.74      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: This example is about {}.
accuracy: 0.7031
precision: 0.8952
recall: 0.4571
f1: 0.6052
--------------- Confusion Matrix ---------------
[[2750  154]
 [1563 1316]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.64      0.95      0.76      2904
           1       0.90      0.46      0.61      2879

    accuracy                           0.70      5783
   macro avg       0.77      0.70      0.68      5783
weighted avg       0.77      0.70      0.68      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: The patient's palliative care needs are {}.
accuracy: 0.7213
precision: 0.7802
recall: 0.6127
f1: 0.6864
--------------- Confusion Matrix ---------------
[[2407  497]
 [1115 1764]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.68      0.83      0.75      2904
           1       0.78      0.61      0.69      2879

    accuracy                           0.72      5783
   macro avg       0.73      0.72      0.72      5783
weighted avg       0.73      0.72      0.72      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: The patient's palliative care needs are {}.
accuracy: 0.7131
precision: 0.7370
recall: 0.6589
f1: 0.6958
--------------- Confusion Matrix ---------------
[[2227  677]
 [ 982 1897]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.69      0.77      0.73      2904
           1       0.74      0.66      0.70      2879

    accuracy                           0.71      5783
   macro avg       0.72      0.71      0.71      5783
weighted avg       0.72      0.71      0.71      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: The patient's palliative care needs are {}.
accuracy: 0.5227
precision: 0.5106
recall: 0.9986
f1: 0.6757
--------------- Confusion Matrix ---------------
[[ 148 2756]
 [   4 2875]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.97      0.05      0.10      2904
           1       0.51      1.00      0.68      2879

    accuracy                           0.52      5783
   macro avg       0.74      0.52      0.39      5783
weighted avg       0.74      0.52      0.39      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: The patient's palliative care needs are {}.
accuracy: 0.7890
precision: 0.8630
recall: 0.6850
f1: 0.7637
--------------- Confusion Matrix ---------------
[[2591  313]
 [ 907 1972]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.74      0.89      0.81      2904
           1       0.86      0.68      0.76      2879

    accuracy                           0.79      5783
   macro avg       0.80      0.79      0.79      5783
weighted avg       0.80      0.79      0.79      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: The patient's palliative care needs are {}.
accuracy: 0.5539
precision: 0.5275
recall: 0.9976
f1: 0.6901
--------------- Confusion Matrix ---------------
[[ 331 2573]
 [   7 2872]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.98      0.11      0.20      2904
           1       0.53      1.00      0.69      2879

    accuracy                           0.55      5783
   macro avg       0.75      0.56      0.45      5783
weighted avg       0.75      0.55      0.45      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: The patient's palliative care needs are {}.
accuracy: 0.5532
precision: 0.6860
recall: 0.1890
f1: 0.2963
--------------- Confusion Matrix ---------------
[[2655  249]
 [2335  544]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.53      0.91      0.67      2904
           1       0.69      0.19      0.30      2879

    accuracy                           0.55      5783
   macro avg       0.61      0.55      0.48      5783
weighted avg       0.61      0.55      0.49      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: The patient's palliative care needs are {}.
accuracy: 0.7479
precision: 0.8074
recall: 0.6481
f1: 0.7191
--------------- Confusion Matrix ---------------
[[2459  445]
 [1013 1866]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.71      0.85      0.77      2904
           1       0.81      0.65      0.72      2879

    accuracy                           0.75      5783
   macro avg       0.76      0.75      0.75      5783
weighted avg       0.76      0.75      0.75      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: The patient's palliative care needs are {}.
accuracy: 0.6998
precision: 0.6527
recall: 0.8486
f1: 0.7378
--------------- Confusion Matrix ---------------
[[1604 1300]
 [ 436 2443]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.79      0.55      0.65      2904
           1       0.65      0.85      0.74      2879

    accuracy                           0.70      5783
   macro avg       0.72      0.70      0.69      5783
weighted avg       0.72      0.70      0.69      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: Overall, the patient's care needs are {}.
accuracy: 0.8017
precision: 0.8191
recall: 0.7721
f1: 0.7949
--------------- Confusion Matrix ---------------
[[2413  491]
 [ 656 2223]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.79      0.83      0.81      2904
           1       0.82      0.77      0.79      2879

    accuracy                           0.80      5783
   macro avg       0.80      0.80      0.80      5783
weighted avg       0.80      0.80      0.80      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: Overall, the patient's care needs are {}.
accuracy: 0.7003
precision: 0.6474
recall: 0.8743
f1: 0.7439
--------------- Confusion Matrix ---------------
[[1533 1371]
 [ 362 2517]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.81      0.53      0.64      2904
           1       0.65      0.87      0.74      2879

    accuracy                           0.70      5783
   macro avg       0.73      0.70      0.69      5783
weighted avg       0.73      0.70      0.69      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: Overall, the patient's care needs are {}.
accuracy: 0.6369
precision: 0.5816
recall: 0.9642
f1: 0.7256
--------------- Confusion Matrix ---------------
[[ 907 1997]
 [ 103 2776]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.90      0.31      0.46      2904
           1       0.58      0.96      0.73      2879

    accuracy                           0.64      5783
   macro avg       0.74      0.64      0.59      5783
weighted avg       0.74      0.64      0.59      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: Overall, the patient's care needs are {}.
accuracy: 0.7830
precision: 0.8823
recall: 0.6509
f1: 0.7492
--------------- Confusion Matrix ---------------
[[2654  250]
 [1005 1874]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.73      0.91      0.81      2904
           1       0.88      0.65      0.75      2879

    accuracy                           0.78      5783
   macro avg       0.80      0.78      0.78      5783
weighted avg       0.80      0.78      0.78      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: Overall, the patient's care needs are {}.
accuracy: 0.7849
precision: 0.7298
recall: 0.9017
f1: 0.8067
--------------- Confusion Matrix ---------------
[[1943  961]
 [ 283 2596]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.87      0.67      0.76      2904
           1       0.73      0.90      0.81      2879

    accuracy                           0.78      5783
   macro avg       0.80      0.79      0.78      5783
weighted avg       0.80      0.78      0.78      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: Overall, the patient's care needs are {}.
accuracy: 0.5513
precision: 0.6816
recall: 0.1851
f1: 0.2912
--------------- Confusion Matrix ---------------
[[2655  249]
 [2346  533]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.53      0.91      0.67      2904
           1       0.68      0.19      0.29      2879

    accuracy                           0.55      5783
   macro avg       0.61      0.55      0.48      5783
weighted avg       0.61      0.55      0.48      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: Overall, the patient's care needs are {}.
accuracy: 0.7411
precision: 0.7542
recall: 0.7121
f1: 0.7325
--------------- Confusion Matrix ---------------
[[2236  668]
 [ 829 2050]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.73      0.77      0.75      2904
           1       0.75      0.71      0.73      2879

    accuracy                           0.74      5783
   macro avg       0.74      0.74      0.74      5783
weighted avg       0.74      0.74      0.74      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: Overall, the patient's care needs are {}.
accuracy: 0.8260
precision: 0.8799
recall: 0.7534
f1: 0.8118
--------------- Confusion Matrix ---------------
[[2608  296]
 [ 710 2169]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.79      0.90      0.84      2904
           1       0.88      0.75      0.81      2879

    accuracy                           0.83      5783
   macro avg       0.83      0.83      0.83      5783
weighted avg       0.83      0.83      0.83      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: From this note, it can be inferred that {}.
accuracy: 0.8001
precision: 0.8127
recall: 0.7777
f1: 0.7948
--------------- Confusion Matrix ---------------
[[2388  516]
 [ 640 2239]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.79      0.82      0.81      2904
           1       0.81      0.78      0.79      2879

    accuracy                           0.80      5783
   macro avg       0.80      0.80      0.80      5783
weighted avg       0.80      0.80      0.80      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: From this note, it can be inferred that {}.
accuracy: 0.7550
precision: 0.7596
recall: 0.7430
f1: 0.7512
--------------- Confusion Matrix ---------------
[[2227  677]
 [ 740 2139]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.75      0.77      0.76      2904
           1       0.76      0.74      0.75      2879

    accuracy                           0.75      5783
   macro avg       0.76      0.75      0.75      5783
weighted avg       0.76      0.75      0.75      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: From this note, it can be inferred that {}.
accuracy: 0.7545
precision: 0.6917
recall: 0.9142
f1: 0.7876
--------------- Confusion Matrix ---------------
[[1731 1173]
 [ 247 2632]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.88      0.60      0.71      2904
           1       0.69      0.91      0.79      2879

    accuracy                           0.75      5783
   macro avg       0.78      0.76      0.75      5783
weighted avg       0.78      0.75      0.75      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: From this note, it can be inferred that {}.
accuracy: 0.7996
precision: 0.8707
recall: 0.7016
f1: 0.7771
--------------- Confusion Matrix ---------------
[[2604  300]
 [ 859 2020]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.75      0.90      0.82      2904
           1       0.87      0.70      0.78      2879

    accuracy                           0.80      5783
   macro avg       0.81      0.80      0.80      5783
weighted avg       0.81      0.80      0.80      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: From this note, it can be inferred that {}.
accuracy: 0.8164
precision: 0.7670
recall: 0.9066
f1: 0.8309
--------------- Confusion Matrix ---------------
[[2111  793]
 [ 269 2610]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.89      0.73      0.80      2904
           1       0.77      0.91      0.83      2879

    accuracy                           0.82      5783
   macro avg       0.83      0.82      0.81      5783
weighted avg       0.83      0.82      0.81      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: From this note, it can be inferred that {}.
accuracy: 0.5469
precision: 0.7046
recall: 0.1549
f1: 0.2540
--------------- Confusion Matrix ---------------
[[2717  187]
 [2433  446]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.53      0.94      0.67      2904
           1       0.70      0.15      0.25      2879

    accuracy                           0.55      5783
   macro avg       0.62      0.55      0.46      5783
weighted avg       0.62      0.55      0.47      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: From this note, it can be inferred that {}.
accuracy: 0.7202
precision: 0.7680
recall: 0.6276
f1: 0.6907
--------------- Confusion Matrix ---------------
[[2358  546]
 [1072 1807]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.69      0.81      0.74      2904
           1       0.77      0.63      0.69      2879

    accuracy                           0.72      5783
   macro avg       0.73      0.72      0.72      5783
weighted avg       0.73      0.72      0.72      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: From this note, it can be inferred that {}.
accuracy: 0.8447
precision: 0.8577
recall: 0.8249
f1: 0.8410
--------------- Confusion Matrix ---------------
[[2510  394]
 [ 504 2375]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.83      0.86      0.85      2904
           1       0.86      0.82      0.84      2879

    accuracy                           0.84      5783
   macro avg       0.85      0.84      0.84      5783
weighted avg       0.85      0.84      0.84      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: This clinical note indicates that the patient's care needs are {}.
accuracy: 0.8010
precision: 0.7988
recall: 0.8024
f1: 0.8006
--------------- Confusion Matrix ---------------
[[2322  582]
 [ 569 2310]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.80      0.80      0.80      2904
           1       0.80      0.80      0.80      2879

    accuracy                           0.80      5783
   macro avg       0.80      0.80      0.80      5783
weighted avg       0.80      0.80      0.80      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: This clinical note indicates that the patient's care needs are {}.
accuracy: 0.7136
precision: 0.6763
recall: 0.8149
f1: 0.7391
--------------- Confusion Matrix ---------------
[[1781 1123]
 [ 533 2346]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.77      0.61      0.68      2904
           1       0.68      0.81      0.74      2879

    accuracy                           0.71      5783
   macro avg       0.72      0.71      0.71      5783
weighted avg       0.72      0.71      0.71      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: This clinical note indicates that the patient's care needs are {}.
accuracy: 0.7462
precision: 0.6738
recall: 0.9500
f1: 0.7884
--------------- Confusion Matrix ---------------
[[1580 1324]
 [ 144 2735]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.92      0.54      0.68      2904
           1       0.67      0.95      0.79      2879

    accuracy                           0.75      5783
   macro avg       0.80      0.75      0.74      5783
weighted avg       0.80      0.75      0.74      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: This clinical note indicates that the patient's care needs are {}.
accuracy: 0.7951
precision: 0.8592
recall: 0.7037
f1: 0.7737
--------------- Confusion Matrix ---------------
[[2572  332]
 [ 853 2026]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.75      0.89      0.81      2904
           1       0.86      0.70      0.77      2879

    accuracy                           0.80      5783
   macro avg       0.81      0.79      0.79      5783
weighted avg       0.80      0.80      0.79      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: This clinical note indicates that the patient's care needs are {}.
accuracy: 0.8190
precision: 0.7707
recall: 0.9059
f1: 0.8328
--------------- Confusion Matrix ---------------
[[2128  776]
 [ 271 2608]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.89      0.73      0.80      2904
           1       0.77      0.91      0.83      2879

    accuracy                           0.82      5783
   macro avg       0.83      0.82      0.82      5783
weighted avg       0.83      0.82      0.82      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: This clinical note indicates that the patient's care needs are {}.
accuracy: 0.5480
precision: 0.6568
recall: 0.1928
f1: 0.2981
--------------- Confusion Matrix ---------------
[[2614  290]
 [2324  555]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.53      0.90      0.67      2904
           1       0.66      0.19      0.30      2879

    accuracy                           0.55      5783
   macro avg       0.59      0.55      0.48      5783
weighted avg       0.59      0.55      0.48      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: This clinical note indicates that the patient's care needs are {}.
accuracy: 0.7311
precision: 0.7621
recall: 0.6686
f1: 0.7123
--------------- Confusion Matrix ---------------
[[2303  601]
 [ 954 1925]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.71      0.79      0.75      2904
           1       0.76      0.67      0.71      2879

    accuracy                           0.73      5783
   macro avg       0.73      0.73      0.73      5783
weighted avg       0.73      0.73      0.73      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: This clinical note indicates that the patient's care needs are {}.
accuracy: 0.8425
precision: 0.8502
recall: 0.8298
f1: 0.8399
--------------- Confusion Matrix ---------------
[[2483  421]
 [ 490 2389]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.84      0.86      0.84      2904
           1       0.85      0.83      0.84      2879

    accuracy                           0.84      5783
   macro avg       0.84      0.84      0.84      5783
weighted avg       0.84      0.84      0.84      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: Based on this note, the patient's care needs are {}.
accuracy: 0.7780
precision: 0.8141
recall: 0.7180
f1: 0.7630
--------------- Confusion Matrix ---------------
[[2432  472]
 [ 812 2067]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.75      0.84      0.79      2904
           1       0.81      0.72      0.76      2879

    accuracy                           0.78      5783
   macro avg       0.78      0.78      0.78      5783
weighted avg       0.78      0.78      0.78      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: Based on this note, the patient's care needs are {}.
accuracy: 0.7097
precision: 0.6912
recall: 0.7534
f1: 0.7210
--------------- Confusion Matrix ---------------
[[1935  969]
 [ 710 2169]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.73      0.67      0.70      2904
           1       0.69      0.75      0.72      2879

    accuracy                           0.71      5783
   macro avg       0.71      0.71      0.71      5783
weighted avg       0.71      0.71      0.71      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: Based on this note, the patient's care needs are {}.
accuracy: 0.5981
precision: 0.5562
recall: 0.9535
f1: 0.7026
--------------- Confusion Matrix ---------------
[[ 714 2190]
 [ 134 2745]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.84      0.25      0.38      2904
           1       0.56      0.95      0.70      2879

    accuracy                           0.60      5783
   macro avg       0.70      0.60      0.54      5783
weighted avg       0.70      0.60      0.54      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: Based on this note, the patient's care needs are {}.
accuracy: 0.7762
precision: 0.8761
recall: 0.6412
f1: 0.7405
--------------- Confusion Matrix ---------------
[[2643  261]
 [1033 1846]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.72      0.91      0.80      2904
           1       0.88      0.64      0.74      2879

    accuracy                           0.78      5783
   macro avg       0.80      0.78      0.77      5783
weighted avg       0.80      0.78      0.77      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: Based on this note, the patient's care needs are {}.
accuracy: 0.7977
precision: 0.7496
recall: 0.8913
f1: 0.8143
--------------- Confusion Matrix ---------------
[[2047  857]
 [ 313 2566]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.87      0.70      0.78      2904
           1       0.75      0.89      0.81      2879

    accuracy                           0.80      5783
   macro avg       0.81      0.80      0.80      5783
weighted avg       0.81      0.80      0.80      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: Based on this note, the patient's care needs are {}.
accuracy: 0.5428
precision: 0.6794
recall: 0.1546
f1: 0.2518
--------------- Confusion Matrix ---------------
[[2694  210]
 [2434  445]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.53      0.93      0.67      2904
           1       0.68      0.15      0.25      2879

    accuracy                           0.54      5783
   macro avg       0.60      0.54      0.46      5783
weighted avg       0.60      0.54      0.46      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: Based on this note, the patient's care needs are {}.
accuracy: 0.7081
precision: 0.7240
recall: 0.6686
f1: 0.6952
--------------- Confusion Matrix ---------------
[[2170  734]
 [ 954 1925]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.69      0.75      0.72      2904
           1       0.72      0.67      0.70      2879

    accuracy                           0.71      5783
   macro avg       0.71      0.71      0.71      5783
weighted avg       0.71      0.71      0.71      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: Based on this note, the patient's care needs are {}.
accuracy: 0.8212
precision: 0.8677
recall: 0.7562
f1: 0.8081
--------------- Confusion Matrix ---------------
[[2572  332]
 [ 702 2177]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.79      0.89      0.83      2904
           1       0.87      0.76      0.81      2879

    accuracy                           0.82      5783
   macro avg       0.83      0.82      0.82      5783
weighted avg       0.83      0.82      0.82      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: The patient's condition suggests that {}.
accuracy: 0.7643
precision: 0.8414
recall: 0.6488
f1: 0.7327
--------------- Confusion Matrix ---------------
[[2552  352]
 [1011 1868]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.72      0.88      0.79      2904
           1       0.84      0.65      0.73      2879

    accuracy                           0.76      5783
   macro avg       0.78      0.76      0.76      5783
weighted avg       0.78      0.76      0.76      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: The patient's condition suggests that {}.
accuracy: 0.7453
precision: 0.7332
recall: 0.7676
f1: 0.7500
--------------- Confusion Matrix ---------------
[[2100  804]
 [ 669 2210]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.76      0.72      0.74      2904
           1       0.73      0.77      0.75      2879

    accuracy                           0.75      5783
   macro avg       0.75      0.75      0.75      5783
weighted avg       0.75      0.75      0.75      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: The patient's condition suggests that {}.
accuracy: 0.7323
precision: 0.6592
recall: 0.9569
f1: 0.7807
--------------- Confusion Matrix ---------------
[[1480 1424]
 [ 124 2755]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.92      0.51      0.66      2904
           1       0.66      0.96      0.78      2879

    accuracy                           0.73      5783
   macro avg       0.79      0.73      0.72      5783
weighted avg       0.79      0.73      0.72      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: The patient's condition suggests that {}.
accuracy: 0.7821
precision: 0.8599
recall: 0.6718
f1: 0.7543
--------------- Confusion Matrix ---------------
[[2589  315]
 [ 945 1934]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.73      0.89      0.80      2904
           1       0.86      0.67      0.75      2879

    accuracy                           0.78      5783
   macro avg       0.80      0.78      0.78      5783
weighted avg       0.80      0.78      0.78      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: The patient's condition suggests that {}.
accuracy: 0.6753
precision: 0.6094
recall: 0.9687
f1: 0.7481
--------------- Confusion Matrix ---------------
[[1116 1788]
 [  90 2789]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.93      0.38      0.54      2904
           1       0.61      0.97      0.75      2879

    accuracy                           0.68      5783
   macro avg       0.77      0.68      0.65      5783
weighted avg       0.77      0.68      0.65      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: The patient's condition suggests that {}.
accuracy: 0.5779
precision: 0.6837
recall: 0.2831
f1: 0.4004
--------------- Confusion Matrix ---------------
[[2527  377]
 [2064  815]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.55      0.87      0.67      2904
           1       0.68      0.28      0.40      2879

    accuracy                           0.58      5783
   macro avg       0.62      0.58      0.54      5783
weighted avg       0.62      0.58      0.54      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: The patient's condition suggests that {}.
accuracy: 0.7474
precision: 0.7708
recall: 0.7009
f1: 0.7342
--------------- Confusion Matrix ---------------
[[2304  600]
 [ 861 2018]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.73      0.79      0.76      2904
           1       0.77      0.70      0.73      2879

    accuracy                           0.75      5783
   macro avg       0.75      0.75      0.75      5783
weighted avg       0.75      0.75      0.75      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: The patient's condition suggests that {}.
accuracy: 0.8376
precision: 0.8742
recall: 0.7871
f1: 0.8284
--------------- Confusion Matrix ---------------
[[2578  326]
 [ 613 2266]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.81      0.89      0.85      2904
           1       0.87      0.79      0.83      2879

    accuracy                           0.84      5783
   macro avg       0.84      0.84      0.84      5783
weighted avg       0.84      0.84      0.84      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: This note suggests that the patient is experiencing {}.
accuracy: 0.7387
precision: 0.8577
recall: 0.5696
f1: 0.6846
--------------- Confusion Matrix ---------------
[[2632  272]
 [1239 1640]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.68      0.91      0.78      2904
           1       0.86      0.57      0.68      2879

    accuracy                           0.74      5783
   macro avg       0.77      0.74      0.73      5783
weighted avg       0.77      0.74      0.73      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: This note suggests that the patient is experiencing {}.
accuracy: 0.7360
precision: 0.7284
recall: 0.7489
f1: 0.7385
--------------- Confusion Matrix ---------------
[[2100  804]
 [ 723 2156]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.74      0.72      0.73      2904
           1       0.73      0.75      0.74      2879

    accuracy                           0.74      5783
   macro avg       0.74      0.74      0.74      5783
weighted avg       0.74      0.74      0.74      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: This note suggests that the patient is experiencing {}.
accuracy: 0.7560
precision: 0.6986
recall: 0.8968
f1: 0.7854
--------------- Confusion Matrix ---------------
[[1790 1114]
 [ 297 2582]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.86      0.62      0.72      2904
           1       0.70      0.90      0.79      2879

    accuracy                           0.76      5783
   macro avg       0.78      0.76      0.75      5783
weighted avg       0.78      0.76      0.75      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: This note suggests that the patient is experiencing {}.
accuracy: 0.7674
precision: 0.8835
recall: 0.6138
f1: 0.7243
--------------- Confusion Matrix ---------------
[[2671  233]
 [1112 1767]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.71      0.92      0.80      2904
           1       0.88      0.61      0.72      2879

    accuracy                           0.77      5783
   macro avg       0.79      0.77      0.76      5783
weighted avg       0.79      0.77      0.76      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: This note suggests that the patient is experiencing {}.
accuracy: 0.7965
precision: 0.7513
recall: 0.8836
f1: 0.8121
--------------- Confusion Matrix ---------------
[[2062  842]
 [ 335 2544]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.86      0.71      0.78      2904
           1       0.75      0.88      0.81      2879

    accuracy                           0.80      5783
   macro avg       0.81      0.80      0.80      5783
weighted avg       0.81      0.80      0.79      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: This note suggests that the patient is experiencing {}.
accuracy: 0.5620
precision: 0.6798
recall: 0.2272
f1: 0.3405
--------------- Confusion Matrix ---------------
[[2596  308]
 [2225  654]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.54      0.89      0.67      2904
           1       0.68      0.23      0.34      2879

    accuracy                           0.56      5783
   macro avg       0.61      0.56      0.51      5783
weighted avg       0.61      0.56      0.51      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: This note suggests that the patient is experiencing {}.
accuracy: 0.7306
precision: 0.7628
recall: 0.6659
f1: 0.7111
--------------- Confusion Matrix ---------------
[[2308  596]
 [ 962 1917]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.71      0.79      0.75      2904
           1       0.76      0.67      0.71      2879

    accuracy                           0.73      5783
   macro avg       0.73      0.73      0.73      5783
weighted avg       0.73      0.73      0.73      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: This note suggests that the patient is experiencing {}.
accuracy: 0.8091
precision: 0.8455
recall: 0.7544
f1: 0.7974
--------------- Confusion Matrix ---------------
[[2507  397]
 [ 707 2172]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.78      0.86      0.82      2904
           1       0.85      0.75      0.80      2879

    accuracy                           0.81      5783
   macro avg       0.81      0.81      0.81      5783
weighted avg       0.81      0.81      0.81      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: The patient's current situation reflects {}.
accuracy: 0.7562
precision: 0.7841
recall: 0.7041
f1: 0.7419
--------------- Confusion Matrix ---------------
[[2346  558]
 [ 852 2027]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.73      0.81      0.77      2904
           1       0.78      0.70      0.74      2879

    accuracy                           0.76      5783
   macro avg       0.76      0.76      0.76      5783
weighted avg       0.76      0.76      0.76      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: The patient's current situation reflects {}.
accuracy: 0.6965
precision: 0.6377
recall: 0.9038
f1: 0.7478
--------------- Confusion Matrix ---------------
[[1426 1478]
 [ 277 2602]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.84      0.49      0.62      2904
           1       0.64      0.90      0.75      2879

    accuracy                           0.70      5783
   macro avg       0.74      0.70      0.68      5783
weighted avg       0.74      0.70      0.68      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: The patient's current situation reflects {}.
accuracy: 0.6370
precision: 0.5818
recall: 0.9639
f1: 0.7256
--------------- Confusion Matrix ---------------
[[ 909 1995]
 [ 104 2775]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.90      0.31      0.46      2904
           1       0.58      0.96      0.73      2879

    accuracy                           0.64      5783
   macro avg       0.74      0.64      0.59      5783
weighted avg       0.74      0.64      0.59      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: The patient's current situation reflects {}.
accuracy: 0.8049
precision: 0.8251
recall: 0.7718
f1: 0.7976
--------------- Confusion Matrix ---------------
[[2433  471]
 [ 657 2222]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.79      0.84      0.81      2904
           1       0.83      0.77      0.80      2879

    accuracy                           0.80      5783
   macro avg       0.81      0.80      0.80      5783
weighted avg       0.81      0.80      0.80      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: The patient's current situation reflects {}.
accuracy: 0.7704
precision: 0.7193
recall: 0.8836
f1: 0.7930
--------------- Confusion Matrix ---------------
[[1911  993]
 [ 335 2544]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.85      0.66      0.74      2904
           1       0.72      0.88      0.79      2879

    accuracy                           0.77      5783
   macro avg       0.79      0.77      0.77      5783
weighted avg       0.79      0.77      0.77      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: The patient's current situation reflects {}.
accuracy: 0.5746
precision: 0.6641
recall: 0.2945
f1: 0.4081
--------------- Confusion Matrix ---------------
[[2475  429]
 [2031  848]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.55      0.85      0.67      2904
           1       0.66      0.29      0.41      2879

    accuracy                           0.57      5783
   macro avg       0.61      0.57      0.54      5783
weighted avg       0.61      0.57      0.54      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: The patient's current situation reflects {}.
accuracy: 0.7437
precision: 0.7633
recall: 0.7034
f1: 0.7321
--------------- Confusion Matrix ---------------
[[2276  628]
 [ 854 2025]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.73      0.78      0.75      2904
           1       0.76      0.70      0.73      2879

    accuracy                           0.74      5783
   macro avg       0.75      0.74      0.74      5783
weighted avg       0.75      0.74      0.74      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: The patient's current situation reflects {}.
accuracy: 0.8177
precision: 0.8051
recall: 0.8364
f1: 0.8204
--------------- Confusion Matrix ---------------
[[2321  583]
 [ 471 2408]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.83      0.80      0.81      2904
           1       0.81      0.84      0.82      2879

    accuracy                           0.82      5783
   macro avg       0.82      0.82      0.82      5783
weighted avg       0.82      0.82      0.82      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: The patient's symptoms and care needs are {}.
accuracy: 0.7185
precision: 0.8026
recall: 0.5762
f1: 0.6708
--------------- Confusion Matrix ---------------
[[2496  408]
 [1220 1659]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.67      0.86      0.75      2904
           1       0.80      0.58      0.67      2879

    accuracy                           0.72      5783
   macro avg       0.74      0.72      0.71      5783
weighted avg       0.74      0.72      0.71      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: The patient's symptoms and care needs are {}.
accuracy: 0.6542
precision: 0.6224
recall: 0.7763
f1: 0.6909
--------------- Confusion Matrix ---------------
[[1548 1356]
 [ 644 2235]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.71      0.53      0.61      2904
           1       0.62      0.78      0.69      2879

    accuracy                           0.65      5783
   macro avg       0.66      0.65      0.65      5783
weighted avg       0.66      0.65      0.65      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: The patient's symptoms and care needs are {}.
accuracy: 0.5705
precision: 0.5385
recall: 0.9594
f1: 0.6898
--------------- Confusion Matrix ---------------
[[ 537 2367]
 [ 117 2762]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.82      0.18      0.30      2904
           1       0.54      0.96      0.69      2879

    accuracy                           0.57      5783
   macro avg       0.68      0.57      0.50      5783
weighted avg       0.68      0.57      0.49      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: The patient's symptoms and care needs are {}.
accuracy: 0.8004
precision: 0.8644
recall: 0.7107
f1: 0.7800
--------------- Confusion Matrix ---------------
[[2583  321]
 [ 833 2046]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.76      0.89      0.82      2904
           1       0.86      0.71      0.78      2879

    accuracy                           0.80      5783
   macro avg       0.81      0.80      0.80      5783
weighted avg       0.81      0.80      0.80      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: The patient's symptoms and care needs are {}.
accuracy: 0.7612
precision: 0.7177
recall: 0.8576
f1: 0.7815
--------------- Confusion Matrix ---------------
[[1933  971]
 [ 410 2469]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.83      0.67      0.74      2904
           1       0.72      0.86      0.78      2879

    accuracy                           0.76      5783
   macro avg       0.77      0.76      0.76      5783
weighted avg       0.77      0.76      0.76      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: The patient's symptoms and care needs are {}.
accuracy: 0.5552
precision: 0.7123
recall: 0.1789
f1: 0.2860
--------------- Confusion Matrix ---------------
[[2696  208]
 [2364  515]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.53      0.93      0.68      2904
           1       0.71      0.18      0.29      2879

    accuracy                           0.56      5783
   macro avg       0.62      0.55      0.48      5783
weighted avg       0.62      0.56      0.48      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: The patient's symptoms and care needs are {}.
accuracy: 0.7474
precision: 0.8096
recall: 0.6440
f1: 0.7174
--------------- Confusion Matrix ---------------
[[2468  436]
 [1025 1854]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.71      0.85      0.77      2904
           1       0.81      0.64      0.72      2879

    accuracy                           0.75      5783
   macro avg       0.76      0.75      0.74      5783
weighted avg       0.76      0.75      0.74      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: The patient's symptoms and care needs are {}.
accuracy: 0.8146
precision: 0.8411
recall: 0.7739
f1: 0.8061
--------------- Confusion Matrix ---------------
[[2483  421]
 [ 651 2228]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.79      0.86      0.82      2904
           1       0.84      0.77      0.81      2879

    accuracy                           0.81      5783
   macro avg       0.82      0.81      0.81      5783
weighted avg       0.82      0.81      0.81      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: The patient's care is {}.
accuracy: 0.7124
precision: 0.8231
recall: 0.5380
f1: 0.6507
--------------- Confusion Matrix ---------------
[[2571  333]
 [1330 1549]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.66      0.89      0.76      2904
           1       0.82      0.54      0.65      2879

    accuracy                           0.71      5783
   macro avg       0.74      0.71      0.70      5783
weighted avg       0.74      0.71      0.70      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: The patient's care is {}.
accuracy: 0.7259
precision: 0.7187
recall: 0.7385
f1: 0.7285
--------------- Confusion Matrix ---------------
[[2072  832]
 [ 753 2126]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.73      0.71      0.72      2904
           1       0.72      0.74      0.73      2879

    accuracy                           0.73      5783
   macro avg       0.73      0.73      0.73      5783
weighted avg       0.73      0.73      0.73      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: The patient's care is {}.
accuracy: 0.6331
precision: 0.5818
recall: 0.9347
f1: 0.7172
--------------- Confusion Matrix ---------------
[[ 970 1934]
 [ 188 2691]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.84      0.33      0.48      2904
           1       0.58      0.93      0.72      2879

    accuracy                           0.63      5783
   macro avg       0.71      0.63      0.60      5783
weighted avg       0.71      0.63      0.60      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: The patient's care is {}.
accuracy: 0.7778
precision: 0.8704
recall: 0.6506
f1: 0.7446
--------------- Confusion Matrix ---------------
[[2625  279]
 [1006 1873]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.72      0.90      0.80      2904
           1       0.87      0.65      0.74      2879

    accuracy                           0.78      5783
   macro avg       0.80      0.78      0.77      5783
weighted avg       0.80      0.78      0.77      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: The patient's care is {}.
accuracy: 0.7942
precision: 0.7575
recall: 0.8628
f1: 0.8068
--------------- Confusion Matrix ---------------
[[2109  795]
 [ 395 2484]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.84      0.73      0.78      2904
           1       0.76      0.86      0.81      2879

    accuracy                           0.79      5783
   macro avg       0.80      0.79      0.79      5783
weighted avg       0.80      0.79      0.79      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: The patient's care is {}.
accuracy: 0.5712
precision: 0.6692
recall: 0.2741
f1: 0.3889
--------------- Confusion Matrix ---------------
[[2514  390]
 [2090  789]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.55      0.87      0.67      2904
           1       0.67      0.27      0.39      2879

    accuracy                           0.57      5783
   macro avg       0.61      0.57      0.53      5783
weighted avg       0.61      0.57      0.53      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: The patient's care is {}.
accuracy: 0.7595
precision: 0.8010
recall: 0.6877
f1: 0.7400
--------------- Confusion Matrix ---------------
[[2412  492]
 [ 899 1980]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.73      0.83      0.78      2904
           1       0.80      0.69      0.74      2879

    accuracy                           0.76      5783
   macro avg       0.76      0.76      0.76      5783
weighted avg       0.76      0.76      0.76      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: The patient's care is {}.
accuracy: 0.7973
precision: 0.8662
recall: 0.7013
f1: 0.7750
--------------- Confusion Matrix ---------------
[[2592  312]
 [ 860 2019]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.75      0.89      0.82      2904
           1       0.87      0.70      0.78      2879

    accuracy                           0.80      5783
   macro avg       0.81      0.80      0.80      5783
weighted avg       0.81      0.80      0.80      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: This note indicates a situation where {}.
accuracy: 0.7655
precision: 0.8504
recall: 0.6419
f1: 0.7316
--------------- Confusion Matrix ---------------
[[2579  325]
 [1031 1848]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.71      0.89      0.79      2904
           1       0.85      0.64      0.73      2879

    accuracy                           0.77      5783
   macro avg       0.78      0.76      0.76      5783
weighted avg       0.78      0.77      0.76      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: This note indicates a situation where {}.
accuracy: 0.7455
precision: 0.7201
recall: 0.7996
f1: 0.7577
--------------- Confusion Matrix ---------------
[[2009  895]
 [ 577 2302]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.78      0.69      0.73      2904
           1       0.72      0.80      0.76      2879

    accuracy                           0.75      5783
   macro avg       0.75      0.75      0.74      5783
weighted avg       0.75      0.75      0.74      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: This note indicates a situation where {}.
accuracy: 0.6514
precision: 0.5890
recall: 0.9920
f1: 0.7391
--------------- Confusion Matrix ---------------
[[ 911 1993]
 [  23 2856]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.98      0.31      0.47      2904
           1       0.59      0.99      0.74      2879

    accuracy                           0.65      5783
   macro avg       0.78      0.65      0.61      5783
weighted avg       0.78      0.65      0.61      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: This note indicates a situation where {}.
accuracy: 0.8086
precision: 0.8796
recall: 0.7131
f1: 0.7876
--------------- Confusion Matrix ---------------
[[2623  281]
 [ 826 2053]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.76      0.90      0.83      2904
           1       0.88      0.71      0.79      2879

    accuracy                           0.81      5783
   macro avg       0.82      0.81      0.81      5783
weighted avg       0.82      0.81      0.81      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: This note indicates a situation where {}.
accuracy: 0.7477
precision: 0.6701
recall: 0.9715
f1: 0.7931
--------------- Confusion Matrix ---------------
[[1527 1377]
 [  82 2797]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.95      0.53      0.68      2904
           1       0.67      0.97      0.79      2879

    accuracy                           0.75      5783
   macro avg       0.81      0.75      0.73      5783
weighted avg       0.81      0.75      0.73      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: This note indicates a situation where {}.
accuracy: 0.5376
precision: 0.6462
recall: 0.1573
f1: 0.2531
--------------- Confusion Matrix ---------------
[[2656  248]
 [2426  453]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.52      0.91      0.67      2904
           1       0.65      0.16      0.25      2879

    accuracy                           0.54      5783
   macro avg       0.58      0.54      0.46      5783
weighted avg       0.58      0.54      0.46      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: This note indicates a situation where {}.
accuracy: 0.7422
precision: 0.7814
recall: 0.6693
f1: 0.7210
--------------- Confusion Matrix ---------------
[[2365  539]
 [ 952 1927]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.71      0.81      0.76      2904
           1       0.78      0.67      0.72      2879

    accuracy                           0.74      5783
   macro avg       0.75      0.74      0.74      5783
weighted avg       0.75      0.74      0.74      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: This note indicates a situation where {}.
accuracy: 0.8373
precision: 0.8646
recall: 0.7982
f1: 0.8301
--------------- Confusion Matrix ---------------
[[2544  360]
 [ 581 2298]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.81      0.88      0.84      2904
           1       0.86      0.80      0.83      2879

    accuracy                           0.84      5783
   macro avg       0.84      0.84      0.84      5783
weighted avg       0.84      0.84      0.84      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: The note documents that {}.
accuracy: 0.7508
precision: 0.8372
recall: 0.6200
f1: 0.7124
--------------- Confusion Matrix ---------------
[[2557  347]
 [1094 1785]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.70      0.88      0.78      2904
           1       0.84      0.62      0.71      2879

    accuracy                           0.75      5783
   macro avg       0.77      0.75      0.75      5783
weighted avg       0.77      0.75      0.75      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: The note documents that {}.
accuracy: 0.7382
precision: 0.7353
recall: 0.7409
f1: 0.7381
--------------- Confusion Matrix ---------------
[[2136  768]
 [ 746 2133]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.74      0.74      0.74      2904
           1       0.74      0.74      0.74      2879

    accuracy                           0.74      5783
   macro avg       0.74      0.74      0.74      5783
weighted avg       0.74      0.74      0.74      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: The note documents that {}.
accuracy: 0.7356
precision: 0.6673
recall: 0.9350
f1: 0.7788
--------------- Confusion Matrix ---------------
[[1562 1342]
 [ 187 2692]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.89      0.54      0.67      2904
           1       0.67      0.94      0.78      2879

    accuracy                           0.74      5783
   macro avg       0.78      0.74      0.73      5783
weighted avg       0.78      0.74      0.72      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: The note documents that {}.
accuracy: 0.7787
precision: 0.8887
recall: 0.6349
f1: 0.7407
--------------- Confusion Matrix ---------------
[[2675  229]
 [1051 1828]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.72      0.92      0.81      2904
           1       0.89      0.63      0.74      2879

    accuracy                           0.78      5783
   macro avg       0.80      0.78      0.77      5783
weighted avg       0.80      0.78      0.77      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: The note documents that {}.
accuracy: 0.7963
precision: 0.7670
recall: 0.8486
f1: 0.8057
--------------- Confusion Matrix ---------------
[[2162  742]
 [ 436 2443]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.83      0.74      0.79      2904
           1       0.77      0.85      0.81      2879

    accuracy                           0.80      5783
   macro avg       0.80      0.80      0.80      5783
weighted avg       0.80      0.80      0.80      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: The note documents that {}.
accuracy: 0.5630
precision: 0.6624
recall: 0.2494
f1: 0.3624
--------------- Confusion Matrix ---------------
[[2538  366]
 [2161  718]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.54      0.87      0.67      2904
           1       0.66      0.25      0.36      2879

    accuracy                           0.56      5783
   macro avg       0.60      0.56      0.51      5783
weighted avg       0.60      0.56      0.52      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: The note documents that {}.
accuracy: 0.7655
precision: 0.7801
recall: 0.7367
f1: 0.7578
--------------- Confusion Matrix ---------------
[[2306  598]
 [ 758 2121]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.75      0.79      0.77      2904
           1       0.78      0.74      0.76      2879

    accuracy                           0.77      5783
   macro avg       0.77      0.77      0.77      5783
weighted avg       0.77      0.77      0.77      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: The note documents that {}.
accuracy: 0.8233
precision: 0.8474
recall: 0.7867
f1: 0.8159
--------------- Confusion Matrix ---------------
[[2496  408]
 [ 614 2265]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.80      0.86      0.83      2904
           1       0.85      0.79      0.82      2879

    accuracy                           0.82      5783
   macro avg       0.82      0.82      0.82      5783
weighted avg       0.82      0.82      0.82      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: The record indicates that {}.
accuracy: 0.8136
precision: 0.7959
recall: 0.8413
f1: 0.8180
--------------- Confusion Matrix ---------------
[[2283  621]
 [ 457 2422]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.83      0.79      0.81      2904
           1       0.80      0.84      0.82      2879

    accuracy                           0.81      5783
   macro avg       0.81      0.81      0.81      5783
weighted avg       0.81      0.81      0.81      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: The record indicates that {}.
accuracy: 0.7731
precision: 0.7389
recall: 0.8416
f1: 0.7869
--------------- Confusion Matrix ---------------
[[2048  856]
 [ 456 2423]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.82      0.71      0.76      2904
           1       0.74      0.84      0.79      2879

    accuracy                           0.77      5783
   macro avg       0.78      0.77      0.77      5783
weighted avg       0.78      0.77      0.77      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: The record indicates that {}.
accuracy: 0.7078
precision: 0.6331
recall: 0.9823
f1: 0.7699
--------------- Confusion Matrix ---------------
[[1265 1639]
 [  51 2828]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.96      0.44      0.60      2904
           1       0.63      0.98      0.77      2879

    accuracy                           0.71      5783
   macro avg       0.80      0.71      0.68      5783
weighted avg       0.80      0.71      0.68      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: The record indicates that {}.
accuracy: 0.8124
precision: 0.8600
recall: 0.7444
f1: 0.7980
--------------- Confusion Matrix ---------------
[[2555  349]
 [ 736 2143]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.78      0.88      0.82      2904
           1       0.86      0.74      0.80      2879

    accuracy                           0.81      5783
   macro avg       0.82      0.81      0.81      5783
weighted avg       0.82      0.81      0.81      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: The record indicates that {}.
accuracy: 0.7781
precision: 0.7102
recall: 0.9364
f1: 0.8078
--------------- Confusion Matrix ---------------
[[1804 1100]
 [ 183 2696]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.91      0.62      0.74      2904
           1       0.71      0.94      0.81      2879

    accuracy                           0.78      5783
   macro avg       0.81      0.78      0.77      5783
weighted avg       0.81      0.78      0.77      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: The record indicates that {}.
accuracy: 0.5450
precision: 0.6281
recall: 0.2112
f1: 0.3161
--------------- Confusion Matrix ---------------
[[2544  360]
 [2271  608]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.53      0.88      0.66      2904
           1       0.63      0.21      0.32      2879

    accuracy                           0.55      5783
   macro avg       0.58      0.54      0.49      5783
weighted avg       0.58      0.55      0.49      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: The record indicates that {}.
accuracy: 0.7724
precision: 0.8098
recall: 0.7096
f1: 0.7564
--------------- Confusion Matrix ---------------
[[2424  480]
 [ 836 2043]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.74      0.83      0.79      2904
           1       0.81      0.71      0.76      2879

    accuracy                           0.77      5783
   macro avg       0.78      0.77      0.77      5783
weighted avg       0.78      0.77      0.77      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: The record indicates that {}.
accuracy: 0.8411
precision: 0.8551
recall: 0.8197
f1: 0.8370
--------------- Confusion Matrix ---------------
[[2504  400]
 [ 519 2360]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.83      0.86      0.84      2904
           1       0.86      0.82      0.84      2879

    accuracy                           0.84      5783
   macro avg       0.84      0.84      0.84      5783
weighted avg       0.84      0.84      0.84      5783

----------------------------------------------




Running zero-shot model: cross-encoder/nli-MiniLM2-L6-H768

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-MiniLM2-L6-H768
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cross-encoder/nli-MiniLM2-L6-H768
Hypothesis Template: The clinical documentation suggests that {}.
accuracy: 0.7743
precision: 0.8507
recall: 0.6631
f1: 0.7453
--------------- Confusion Matrix ---------------
[[2569  335]
 [ 970 1909]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.73      0.88      0.80      2904
           1       0.85      0.66      0.75      2879

    accuracy                           0.77      5783
   macro avg       0.79      0.77      0.77      5783
weighted avg       0.79      0.77      0.77      5783

----------------------------------------------




Running zero-shot model: typeform/distilbert-base-uncased-mnli

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: typeform/distilbert-base-uncased-mnli
Hypothesis Template: The clinical documentation suggests that {}.
accuracy: 0.7289
precision: 0.7829
recall: 0.6301
f1: 0.6982
--------------- Confusion Matrix ---------------
[[2401  503]
 [1065 1814]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.69      0.83      0.75      2904
           1       0.78      0.63      0.70      2879

    accuracy                           0.73      5783
   macro avg       0.74      0.73      0.73      5783
weighted avg       0.74      0.73      0.73      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary
Hypothesis Template: The clinical documentation suggests that {}.
accuracy: 0.6927
precision: 0.6219
recall: 0.9764
f1: 0.7598
--------------- Confusion Matrix ---------------
[[1195 1709]
 [  68 2811]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.95      0.41      0.57      2904
           1       0.62      0.98      0.76      2879

    accuracy                           0.69      5783
   macro avg       0.78      0.69      0.67      5783
weighted avg       0.78      0.69      0.67      5783

----------------------------------------------




Running zero-shot model: tasksource/deberta-small-long-nli

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: tasksource/deberta-small-long-nli
Hypothesis Template: The clinical documentation suggests that {}.
accuracy: 0.7685
precision: 0.8705
recall: 0.6283
f1: 0.7299
--------------- Confusion Matrix ---------------
[[2635  269]
 [1070 1809]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.71      0.91      0.80      2904
           1       0.87      0.63      0.73      2879

    accuracy                           0.77      5783
   macro avg       0.79      0.77      0.76      5783
weighted avg       0.79      0.77      0.76      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33
Hypothesis Template: The clinical documentation suggests that {}.
accuracy: 0.7327
precision: 0.6606
recall: 0.9524
f1: 0.7801
--------------- Confusion Matrix ---------------
[[1495 1409]
 [ 137 2742]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.92      0.51      0.66      2904
           1       0.66      0.95      0.78      2879

    accuracy                           0.73      5783
   macro avg       0.79      0.73      0.72      5783
weighted avg       0.79      0.73      0.72      5783

----------------------------------------------




Running zero-shot model: cmarkea/distilcamembert-base-nli

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

CamembertForSequenceClassification LOAD REPORT from: cmarkea/distilcamembert-base-nli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

----------------------------------------------
--------------- Metric Results ---------------

Model: cmarkea/distilcamembert-base-nli
Hypothesis Template: The clinical documentation suggests that {}.
accuracy: 0.5649
precision: 0.6637
recall: 0.2556
f1: 0.3691
--------------- Confusion Matrix ---------------
[[2531  373]
 [2143  736]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.54      0.87      0.67      2904
           1       0.66      0.26      0.37      2879

    accuracy                           0.56      5783
   macro avg       0.60      0.56      0.52      5783
weighted avg       0.60      0.56      0.52      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33
Hypothesis Template: The clinical documentation suggests that {}.
accuracy: 0.7619
precision: 0.7860
recall: 0.7169
f1: 0.7499
--------------- Confusion Matrix ---------------
[[2342  562]
 [ 815 2064]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.74      0.81      0.77      2904
           1       0.79      0.72      0.75      2879

    accuracy                           0.76      5783
   macro avg       0.76      0.76      0.76      5783
weighted avg       0.76      0.76      0.76      5783

----------------------------------------------




Running zero-shot model: MoritzLaurer/deberta-v3-base-zeroshot-v1

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

----------------------------------------------
--------------- Metric Results ---------------

Model: MoritzLaurer/deberta-v3-base-zeroshot-v1
Hypothesis Template: The clinical documentation suggests that {}.
accuracy: 0.8395
precision: 0.8685
recall: 0.7985
f1: 0.8321
--------------- Confusion Matrix ---------------
[[2556  348]
 [ 580 2299]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.82      0.88      0.85      2904
           1       0.87      0.80      0.83      2879

    accuracy                           0.84      5783
   macro avg       0.84      0.84      0.84      5783
weighted avg       0.84      0.84      0.84      5783

----------------------------------------------

In [10]:
all_df.sort_values(by='accuracy', ascending=False)

,model,hypothesis_template,accuracy,precision,recall,f1
108,MoritzLaurer/deberta-v3-base-zeroshot-v1,"From this note, it can be inferred that {}.",0.844717,0.857710,0.824939,0.841006
109,MoritzLaurer/deberta-v3-base-zeroshot-v1,This clinical note indicates that the patient'...,0.842469,0.850178,0.829802,0.839866
118,MoritzLaurer/deberta-v3-base-zeroshot-v1,The record indicates that {}.,0.841086,0.855072,0.819729,0.837028
119,MoritzLaurer/deberta-v3-base-zeroshot-v1,The clinical documentation suggests that {}.,0.839530,0.868530,0.798541,0.832067
111,MoritzLaurer/deberta-v3-base-zeroshot-v1,The patient's condition suggests that {}.,0.837628,0.874228,0.787079,0.828368
...,...,...,...,...,...,...
78,cmarkea/distilcamembert-base-nli,"From this note, it can be inferred that {}.",0.546948,0.704581,0.154915,0.253986
88,cmarkea/distilcamembert-base-nli,The record indicates that {}.,0.545046,0.628099,0.211184,0.316090
80,cmarkea/distilcamembert-base-nli,"Based on this note, the patient's care needs a...",0.542798,0.679389,0.154568,0.251839
86,cmarkea/distilcamembert-base-nli,This note indicates a situation where {}.,0.537610,0.646220,0.157346,0.253073
31,MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli...,The patient's palliative care needs are {}.,0.522739,0.510567,0.998611,0.675676

In [11]:
all_df.sort_values(by='precision', ascending=False)

,model,hypothesis_template,accuracy,precision,recall,f1
45,tasksource/deberta-small-long-nli,This example is about {}.,0.702231,0.903136,0.450156,0.600834
105,MoritzLaurer/deberta-v3-base-zeroshot-v1,This example is about {}.,0.703095,0.895238,0.457103,0.605197
57,tasksource/deberta-small-long-nli,The note documents that {}.,0.778662,0.888673,0.634943,0.740681
52,tasksource/deberta-small-long-nli,This note suggests that the patient is experie...,0.767422,0.883500,0.613755,0.724329
47,tasksource/deberta-small-long-nli,"Overall, the patient's care needs are {}.",0.782985,0.882298,0.650920,0.749151
...,...,...,...,...,...,...
32,MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli...,"Overall, the patient's care needs are {}.",0.636867,0.581605,0.964224,0.725562
35,MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli...,"Based on this note, the patient's care needs a...",0.598132,0.556231,0.953456,0.702585
39,MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli...,The patient's symptoms and care needs are {}.,0.570465,0.538507,0.959361,0.689810
61,MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-a...,The patient's palliative care needs are {}.,0.553865,0.527456,0.997569,0.690053
31,MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli...,The patient's palliative care needs are {}.,0.522739,0.510567,0.998611,0.675676

In [12]:
all_df.sort_values(by='recall', ascending=False)

,model,hypothesis_template,accuracy,precision,recall,f1
31,MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli...,The patient's palliative care needs are {}.,0.522739,0.510567,0.998611,0.675676
61,MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-a...,The patient's palliative care needs are {}.,0.553865,0.527456,0.997569,0.690053
41,MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli...,This note indicates a situation where {}.,0.651392,0.588987,0.992011,0.739130
43,MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli...,The record indicates that {}.,0.707764,0.633087,0.982286,0.769943
44,MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli...,The clinical documentation suggests that {}.,0.692720,0.621903,0.976381,0.759832
...,...,...,...,...,...,...
84,cmarkea/distilcamembert-base-nli,The patient's symptoms and care needs are {}.,0.555248,0.712310,0.178882,0.285952
75,cmarkea/distilcamembert-base-nli,This example is about {}.,0.547640,0.680384,0.172282,0.274945
86,cmarkea/distilcamembert-base-nli,This note indicates a situation where {}.,0.537610,0.646220,0.157346,0.253073
78,cmarkea/distilcamembert-base-nli,"From this note, it can be inferred that {}.",0.546948,0.704581,0.154915,0.253986
80,cmarkea/distilcamembert-base-nli,"Based on this note, the patient's care needs a...",0.542798,0.679389,0.154568,0.251839

In [13]:
all_df.sort_values(by='f1', ascending=False)

,model,hypothesis_template,accuracy,precision,recall,f1
108,MoritzLaurer/deberta-v3-base-zeroshot-v1,"From this note, it can be inferred that {}.",0.844717,0.857710,0.824939,0.841006
109,MoritzLaurer/deberta-v3-base-zeroshot-v1,This clinical note indicates that the patient'...,0.842469,0.850178,0.829802,0.839866
118,MoritzLaurer/deberta-v3-base-zeroshot-v1,The record indicates that {}.,0.841086,0.855072,0.819729,0.837028
64,MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-a...,This clinical note indicates that the patient'...,0.818952,0.770686,0.905870,0.832828
119,MoritzLaurer/deberta-v3-base-zeroshot-v1,The clinical documentation suggests that {}.,0.839530,0.868530,0.798541,0.832067
...,...,...,...,...,...,...
84,cmarkea/distilcamembert-base-nli,The patient's symptoms and care needs are {}.,0.555248,0.712310,0.178882,0.285952
75,cmarkea/distilcamembert-base-nli,This example is about {}.,0.547640,0.680384,0.172282,0.274945
78,cmarkea/distilcamembert-base-nli,"From this note, it can be inferred that {}.",0.546948,0.704581,0.154915,0.253986
86,cmarkea/distilcamembert-base-nli,This note indicates a situation where {}.,0.537610,0.646220,0.157346,0.253073
80,cmarkea/distilcamembert-base-nli,"Based on this note, the patient's care needs a...",0.542798,0.679389,0.154568,0.251839