In [1]:
# HuggingFace Login
import os
from dotenv import load_dotenv
from huggingface_hub import login
load_dotenv()
hf_token = os.getenv("HUGGING_FACE_TOKEN")
login(hf_token)

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [2]:
import pandas as pd
from datasets import Dataset, ClassLabel
import numpy as np
import random
import torch
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from peft import LoraConfig, get_peft_model
from transformers import TrainingArguments
from transformers import Trainer
from transformers import EarlyStoppingCallback
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.metrics import confusion_matrix, classification_report
from torch.utils.data import DataLoader
import gc
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from transformers import pipeline
from datasets import concatenate_datasets

In [ ]:
ZERO_SHOT_MODELS = [
    "cross-encoder/nli-MiniLM2-L6-H768",
    "typeform/distilbert-base-uncased-mnli",
    "MoritzLaurer/DeBERTa-v3-xsmall-mnli-fever-anli-ling-binary",
    "tasksource/deberta-small-long-nli",
    "MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33",
    "cmarkea/distilcamembert-base-nli",
    "MoritzLaurer/xtremedistil-l6-h256-zeroshot-v1.1-all-33",
    "MoritzLaurer/deberta-v3-base-zeroshot-v1"
]


LABELS = ["met palliative care needs", "unmet palliative care needs"]
LABEL_TO_NUM = {"met palliative care needs": 0, "unmet palliative care needs": 1}
LABEL_EXPANSIONS = {
    "met palliative care needs": [
        "palliative care needs are adequately met",
        "symptoms and care needs are well managed",
        "the patient is receiving appropriate palliative care",
        "care needs are sufficiently addressed"
    ],
    "unmet palliative care needs": [
        "palliative care needs are not adequately met",
        "symptoms or care needs are poorly managed",
        "the patient requires additional palliative care support",
        "care needs are not sufficiently addressed"
    ]
}

HYPOTHESIS_TEMPLATES = [
    # Generic hypothesis templates.
    "This example is about {}.",
    # Generic medical hypothesis templates. 
    "The patient's palliative care needs are {}.",
    "Overall, the patient's care needs are {}.",
    "From this note, it can be inferred that {}.",
    "This clinical note indicates that the patient's care needs are {}.",
    "Based on this note, the patient's care needs are {}.",
    # Clinical language.
    "The patient's condition suggests that {}.",
    "This note suggests that the patient is experiencing {}.",
    "The patient's current situation reflects {}.",
    # Care quality framing.
    "The patient's symptoms and care needs are {}.",
    "The patient's care is {}.",
    # Documentation style focus.
    "This note indicates a situation where {}.",
    "The note documents that {}.",
    "The record indicates that {}.",
    "The clinical documentation suggests that {}.",
]

In [4]:
# Set random states.
def set_random_states(random_state):
    # Set various random seeds.
    np.random.seed(random_state)
    random.seed(random_state)
    torch.manual_seed(random_state)
    torch.cuda.manual_seed_all(random_state)
    os.environ["PYTHONHASHSEED"] = str(random_state)
    os.environ["TOKENIZERS_PARALLELISM"] = "false"
    try:
        torch.use_deterministic_algorithms(True)
    except Exception:
        pass
    return random_state

RANDOM_STATE = set_random_states(1618)

In [5]:
# Load the dataset
df = pd.read_csv("./dataSyntheticAll.csv")
dataset = Dataset.from_pandas(df)

# Map dataset labels to 1s or 0s.
label_map = {
    "met palliative care needs": 0,
    "unmet palliative care needs": 1
}

dataset = dataset.map(lambda x: {"label": label_map[f"{x["needs"]} palliative care needs"]})


label_feature = ClassLabel(names=["met palliative care needs", "unmet palliative care needs"])
dataset = dataset.cast_column("label", label_feature)

Map:   0%|          | 0/5783 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/5783 [00:00<?, ? examples/s]

In [6]:
# Split the dataset. (80/10/10)
dataset = dataset.train_test_split(test_size=0.2, seed=RANDOM_STATE, stratify_by_column="label")

train_dataset = dataset["train"]
temp_dataset = dataset["test"]

temp_split = temp_dataset.train_test_split(test_size=0.5, seed=RANDOM_STATE, stratify_by_column="label")

val_dataset = temp_split["train"]
test_dataset = temp_split["test"]

all_dataset = concatenate_datasets([train_dataset, val_dataset, test_dataset])

# Check distributions.
def check_distribution(dataset, name):
    df = dataset.to_pandas()
    counts = df["label"].value_counts(normalize=True)
    print(f"{name} distribution:")
    print(counts)

check_distribution(train_dataset, "Train")
check_distribution(val_dataset, "Validation")
check_distribution(test_dataset, "Test")
check_distribution(all_dataset, "All Data")

Train distribution:
label
0    0.502162
1    0.497838
Name: proportion, dtype: float64
Validation distribution:
label
0    0.50173
1    0.49827
Name: proportion, dtype: float64
Test distribution:
label
0    0.502591
1    0.497409
Name: proportion, dtype: float64
All Data distribution:
label
0    0.502162
1    0.497838
Name: proportion, dtype: float64

In [7]:
# Make evaluation function.
def evaluate_model(preds, labels):
    acc = accuracy_score(labels, preds)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="binary"
    )
    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

In [8]:
results = {}
device = 0 if torch.cuda.is_available() else -1

def run_models(dataset, hypo_temp="This clinical note indicates that {}."):
    for model_name in ZERO_SHOT_MODELS:
        print(f"\nRunning zero-shot model: {model_name}")

        classifier = pipeline(
            "zero-shot-classification",
            model=model_name,
            device=device,
        )

        texts = [ex["report"] for ex in dataset]
        true_labels = [ex["label"] for ex in dataset]

        # Flatten expanded labels.
        flat_labels = []
        label_map = {}

        for base_label, expansions in LABEL_EXPANSIONS.items():
            for exp in expansions:
                flat_labels.append(exp)
                label_map[exp] = base_label

        # Run model.
        outputs = classifier(
            texts,
            candidate_labels=flat_labels,
            hypothesis_template=hypo_temp,
            batch_size=16
        )

        preds = []

        # Aggregate scores per base label.
        for o in outputs:
            scores_by_class = {k: 0.0 for k in LABEL_EXPANSIONS.keys()}

            for label, score in zip(o["labels"], o["scores"]):
                base_label = label_map[label]
                scores_by_class[base_label] += score

            # Pick best aggregated label.
            pred = max(scores_by_class, key=scores_by_class.get)
            preds.append(pred)
        numeric_preds = [0 if pred == "met palliative care needs" else 1 for pred in preds]
        metrics = evaluate_model(numeric_preds, true_labels)

        # Inner dictionary creation.
        if model_name not in results:
            results[model_name] = {}  

        results[model_name][hypo_temp] = metrics

        # Output.
        print("----------------------------------------------")
        print("--------------- Metric Results ---------------")
        print(f"\nModel: {model_name} \nHypothesis Template: {hypo_temp}")
        for k, v in metrics.items():
            print(f"{k}: {v:.4f}")

        print("--------------- Confusion Matrix ---------------")
        print(confusion_matrix(true_labels, numeric_preds))

        print("--------------- Classification Report ---------------")
        print(classification_report(true_labels, numeric_preds))

        print("----------------------------------------------\n\n\n")

        # Free memory.
        del classifier
        torch.cuda.empty_cache()
        gc.collect()

    return results

In [9]:
# Run all hypothesis templates.
test_results = []
for template in HYPOTHESIS_TEMPLATES:
    test_results.append(run_models(test_dataset, hypo_temp=template))

# Save in DataFrame.
rows = []

for model_name, templates in results.items():
    for hypo_template, metrics in templates.items():
        row = {"model": model_name, "hypothesis_template": hypo_template}
        row.update(metrics)
        rows.append(row)

# Save DataFrame.
test_df = pd.DataFrame(rows)
test_df.to_csv('./test_data_all_zero_shot_results.csv', index=False)

Running zero-shot model: intfloat/e5-base-v2

config.json:   0%|          | 0.00/650 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: This example is about {}.
accuracy: 0.5147
precision: 0.8182
recall: 0.0312
f1: 0.0602
--------------- Confusion Matrix ---------------
[[289   2]
 [279   9]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.51      0.99      0.67       291
           1       0.82      0.03      0.06       288

    accuracy                           0.51       579
   macro avg       0.66      0.51      0.37       579
weighted avg       0.66      0.51      0.37       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: The patient's palliative care needs are {}.
accuracy: 0.5060
precision: 0.5417
recall: 0.0451
f1: 0.0833
--------------- Confusion Matrix ---------------
[[280  11]
 [275  13]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.50      0.96      0.66       291
           1       0.54      0.05      0.08       288

    accuracy                           0.51       579
   macro avg       0.52      0.50      0.37       579
weighted avg       0.52      0.51      0.37       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: Overall, the patient's care needs are {}.
accuracy: 0.5078
precision: 0.5405
recall: 0.0694
f1: 0.1231
--------------- Confusion Matrix ---------------
[[274  17]
 [268  20]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.51      0.94      0.66       291
           1       0.54      0.07      0.12       288

    accuracy                           0.51       579
   macro avg       0.52      0.51      0.39       579
weighted avg       0.52      0.51      0.39       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: From this note, it can be inferred that {}.
accuracy: 0.6908
precision: 0.7795
recall: 0.5278
f1: 0.6294
--------------- Confusion Matrix ---------------
[[248  43]
 [136 152]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.65      0.85      0.73       291
           1       0.78      0.53      0.63       288

    accuracy                           0.69       579
   macro avg       0.71      0.69      0.68       579
weighted avg       0.71      0.69      0.68       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: This clinical note indicates that the patient's care needs are {}.
accuracy: 0.4922
precision: 0.4000
recall: 0.0417
f1: 0.0755
--------------- Confusion Matrix ---------------
[[273  18]
 [276  12]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.50      0.94      0.65       291
           1       0.40      0.04      0.08       288

    accuracy                           0.49       579
   macro avg       0.45      0.49      0.36       579
weighted avg       0.45      0.49      0.36       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: Based on this note, the patient's care needs are {}.
accuracy: 0.5734
precision: 0.5504
recall: 0.7778
f1: 0.6446
--------------- Confusion Matrix ---------------
[[108 183]
 [ 64 224]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.63      0.37      0.47       291
           1       0.55      0.78      0.64       288

    accuracy                           0.57       579
   macro avg       0.59      0.57      0.56       579
weighted avg       0.59      0.57      0.56       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: The patient's condition suggests that {}.
accuracy: 0.5147
precision: 0.8889
recall: 0.0278
f1: 0.0539
--------------- Confusion Matrix ---------------
[[290   1]
 [280   8]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.51      1.00      0.67       291
           1       0.89      0.03      0.05       288

    accuracy                           0.51       579
   macro avg       0.70      0.51      0.36       579
weighted avg       0.70      0.51      0.37       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: This note suggests that the patient is experiencing {}.
accuracy: 0.6114
precision: 0.6981
recall: 0.3854
f1: 0.4966
--------------- Confusion Matrix ---------------
[[243  48]
 [177 111]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.58      0.84      0.68       291
           1       0.70      0.39      0.50       288

    accuracy                           0.61       579
   macro avg       0.64      0.61      0.59       579
weighted avg       0.64      0.61      0.59       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: The patient's current situation reflects {}.
accuracy: 0.4093
precision: 0.4462
recall: 0.7778
f1: 0.5671
--------------- Confusion Matrix ---------------
[[ 13 278]
 [ 64 224]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.17      0.04      0.07       291
           1       0.45      0.78      0.57       288

    accuracy                           0.41       579
   macro avg       0.31      0.41      0.32       579
weighted avg       0.31      0.41      0.32       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: The patient's symptoms and care needs are {}.
accuracy: 0.3333
precision: 0.3399
recall: 0.3611
f1: 0.3502
--------------- Confusion Matrix ---------------
[[ 89 202]
 [184 104]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.33      0.31      0.32       291
           1       0.34      0.36      0.35       288

    accuracy                           0.33       579
   macro avg       0.33      0.33      0.33       579
weighted avg       0.33      0.33      0.33       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: The patient's care is {}.
accuracy: 0.4957
precision: 0.4965
recall: 0.9965
f1: 0.6628
--------------- Confusion Matrix ---------------
[[  0 291]
 [  1 287]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       291
           1       0.50      1.00      0.66       288

    accuracy                           0.50       579
   macro avg       0.25      0.50      0.33       579
weighted avg       0.25      0.50      0.33       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: This note indicates a situation where {}.
accuracy: 0.5371
precision: 0.5187
recall: 0.9653
f1: 0.6748
--------------- Confusion Matrix ---------------
[[ 33 258]
 [ 10 278]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.77      0.11      0.20       291
           1       0.52      0.97      0.67       288

    accuracy                           0.54       579
   macro avg       0.64      0.54      0.44       579
weighted avg       0.64      0.54      0.43       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: The note documents that {}.
accuracy: 0.4888
precision: 0.4929
recall: 0.9688
f1: 0.6534
--------------- Confusion Matrix ---------------
[[  4 287]
 [  9 279]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.31      0.01      0.03       291
           1       0.49      0.97      0.65       288

    accuracy                           0.49       579
   macro avg       0.40      0.49      0.34       579
weighted avg       0.40      0.49      0.34       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: The record indicates that {}.
accuracy: 0.5009
precision: 0.4991
recall: 1.0000
f1: 0.6659
--------------- Confusion Matrix ---------------
[[  2 289]
 [  0 288]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       1.00      0.01      0.01       291
           1       0.50      1.00      0.67       288

    accuracy                           0.50       579
   macro avg       0.75      0.50      0.34       579
weighted avg       0.75      0.50      0.34       579

----------------------------------------------




Running zero-shot model: intfloat/e5-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

----------------------------------------------
--------------- Metric Results ---------------

Model: intfloat/e5-base-v2
Hypothesis Template: The clinical documentation suggests that {}.
accuracy: 0.5026
precision: 0.0000
recall: 0.0000
f1: 0.0000
--------------- Confusion Matrix ---------------
[[291   0]
 [288   0]]
--------------- Classification Report ---------------
              precision    recall  f1-score   support

           0       0.50      1.00      0.67       291
           1       0.00      0.00      0.00       288

    accuracy                           0.50       579
   macro avg       0.25      0.50      0.33       579
weighted avg       0.25      0.50      0.34       579

----------------------------------------------

/home/isabel/anaconda3/envs/realData/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/isabel/anaconda3/envs/realData/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/isabel/anaconda3/envs/realData/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/isabel/anaconda3/envs/realData/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [10]:
test_df.sort_values(by='accuracy', ascending=False)

,model,hypothesis_template,accuracy,precision,recall,f1
3,intfloat/e5-base-v2,"From this note, it can be inferred that {}.",0.690846,0.779487,0.527778,0.629400
7,intfloat/e5-base-v2,This note suggests that the patient is experie...,0.611399,0.698113,0.385417,0.496644
5,intfloat/e5-base-v2,"Based on this note, the patient's care needs a...",0.573402,0.550369,0.777778,0.644604
11,intfloat/e5-base-v2,This note indicates a situation where {}.,0.537133,0.518657,0.965278,0.674757
0,intfloat/e5-base-v2,This example is about {}.,0.514680,0.818182,0.031250,0.060201
6,intfloat/e5-base-v2,The patient's condition suggests that {}.,0.514680,0.888889,0.027778,0.053872
2,intfloat/e5-base-v2,"Overall, the patient's care needs are {}.",0.507772,0.540541,0.069444,0.123077
1,intfloat/e5-base-v2,The patient's palliative care needs are {}.,0.506045,0.541667,0.045139,0.083333
14,intfloat/e5-base-v2,The clinical documentation suggests that {}.,0.502591,0.000000,0.000000,0.000000
13,intfloat/e5-base-v2,The record indicates that {}.,0.500864,0.499133,1.000000,0.665896
10,intfloat/e5-base-v2,The patient's care is {}.,0.495682,0.496540,0.996528,0.662818
4,intfloat/e5-base-v2,This clinical note indicates that the patient'...,0.492228,0.400000,0.041667,0.075472
12,intfloat/e5-base-v2,The note documents that {}.,0.488774,0.492933,0.968750,0.653396
8,intfloat/e5-base-v2,The patient's current situation reflects {}.,0.409326,0.446215,0.777778,0.567089
9,intfloat/e5-base-v2,The patient's symptoms and care needs are {}.,0.333333,0.339869,0.361111,0.350168

In [11]:
test_df.sort_values(by='precision', ascending=False)

,model,hypothesis_template,accuracy,precision,recall,f1
6,intfloat/e5-base-v2,The patient's condition suggests that {}.,0.514680,0.888889,0.027778,0.053872
0,intfloat/e5-base-v2,This example is about {}.,0.514680,0.818182,0.031250,0.060201
3,intfloat/e5-base-v2,"From this note, it can be inferred that {}.",0.690846,0.779487,0.527778,0.629400
7,intfloat/e5-base-v2,This note suggests that the patient is experie...,0.611399,0.698113,0.385417,0.496644
5,intfloat/e5-base-v2,"Based on this note, the patient's care needs a...",0.573402,0.550369,0.777778,0.644604
1,intfloat/e5-base-v2,The patient's palliative care needs are {}.,0.506045,0.541667,0.045139,0.083333
2,intfloat/e5-base-v2,"Overall, the patient's care needs are {}.",0.507772,0.540541,0.069444,0.123077
11,intfloat/e5-base-v2,This note indicates a situation where {}.,0.537133,0.518657,0.965278,0.674757
13,intfloat/e5-base-v2,The record indicates that {}.,0.500864,0.499133,1.000000,0.665896
10,intfloat/e5-base-v2,The patient's care is {}.,0.495682,0.496540,0.996528,0.662818
12,intfloat/e5-base-v2,The note documents that {}.,0.488774,0.492933,0.968750,0.653396
8,intfloat/e5-base-v2,The patient's current situation reflects {}.,0.409326,0.446215,0.777778,0.567089
4,intfloat/e5-base-v2,This clinical note indicates that the patient'...,0.492228,0.400000,0.041667,0.075472
9,intfloat/e5-base-v2,The patient's symptoms and care needs are {}.,0.333333,0.339869,0.361111,0.350168
14,intfloat/e5-base-v2,The clinical documentation suggests that {}.,0.502591,0.000000,0.000000,0.000000

In [12]:
test_df.sort_values(by='recall', ascending=False)

,model,hypothesis_template,accuracy,precision,recall,f1
13,intfloat/e5-base-v2,The record indicates that {}.,0.500864,0.499133,1.000000,0.665896
10,intfloat/e5-base-v2,The patient's care is {}.,0.495682,0.496540,0.996528,0.662818
12,intfloat/e5-base-v2,The note documents that {}.,0.488774,0.492933,0.968750,0.653396
11,intfloat/e5-base-v2,This note indicates a situation where {}.,0.537133,0.518657,0.965278,0.674757
5,intfloat/e5-base-v2,"Based on this note, the patient's care needs a...",0.573402,0.550369,0.777778,0.644604
8,intfloat/e5-base-v2,The patient's current situation reflects {}.,0.409326,0.446215,0.777778,0.567089
3,intfloat/e5-base-v2,"From this note, it can be inferred that {}.",0.690846,0.779487,0.527778,0.629400
7,intfloat/e5-base-v2,This note suggests that the patient is experie...,0.611399,0.698113,0.385417,0.496644
9,intfloat/e5-base-v2,The patient's symptoms and care needs are {}.,0.333333,0.339869,0.361111,0.350168
2,intfloat/e5-base-v2,"Overall, the patient's care needs are {}.",0.507772,0.540541,0.069444,0.123077
1,intfloat/e5-base-v2,The patient's palliative care needs are {}.,0.506045,0.541667,0.045139,0.083333
4,intfloat/e5-base-v2,This clinical note indicates that the patient'...,0.492228,0.400000,0.041667,0.075472
0,intfloat/e5-base-v2,This example is about {}.,0.514680,0.818182,0.031250,0.060201
6,intfloat/e5-base-v2,The patient's condition suggests that {}.,0.514680,0.888889,0.027778,0.053872
14,intfloat/e5-base-v2,The clinical documentation suggests that {}.,0.502591,0.000000,0.000000,0.000000

In [13]:
test_df.sort_values(by='f1', ascending=False)

,model,hypothesis_template,accuracy,precision,recall,f1
11,intfloat/e5-base-v2,This note indicates a situation where {}.,0.537133,0.518657,0.965278,0.674757
13,intfloat/e5-base-v2,The record indicates that {}.,0.500864,0.499133,1.000000,0.665896
10,intfloat/e5-base-v2,The patient's care is {}.,0.495682,0.496540,0.996528,0.662818
12,intfloat/e5-base-v2,The note documents that {}.,0.488774,0.492933,0.968750,0.653396
5,intfloat/e5-base-v2,"Based on this note, the patient's care needs a...",0.573402,0.550369,0.777778,0.644604
3,intfloat/e5-base-v2,"From this note, it can be inferred that {}.",0.690846,0.779487,0.527778,0.629400
8,intfloat/e5-base-v2,The patient's current situation reflects {}.,0.409326,0.446215,0.777778,0.567089
7,intfloat/e5-base-v2,This note suggests that the patient is experie...,0.611399,0.698113,0.385417,0.496644
9,intfloat/e5-base-v2,The patient's symptoms and care needs are {}.,0.333333,0.339869,0.361111,0.350168
2,intfloat/e5-base-v2,"Overall, the patient's care needs are {}.",0.507772,0.540541,0.069444,0.123077
1,intfloat/e5-base-v2,The patient's palliative care needs are {}.,0.506045,0.541667,0.045139,0.083333
4,intfloat/e5-base-v2,This clinical note indicates that the patient'...,0.492228,0.400000,0.041667,0.075472
0,intfloat/e5-base-v2,This example is about {}.,0.514680,0.818182,0.031250,0.060201
6,intfloat/e5-base-v2,The patient's condition suggests that {}.,0.514680,0.888889,0.027778,0.053872
14,intfloat/e5-base-v2,The clinical documentation suggests that {}.,0.502591,0.000000,0.000000,0.000000